baseURL = "https://gobuffalo.io/"
languageCode = "en-us"
title = "The Buffalo Framework"
defaultContentLanguage = 'en'

[params]
    docsSections = ["getting_started", "request_handling"]
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2

    [languages.en.params]
      copyRight = "Copyright © 2022 Buffalo. All rights reserved."
      logoCredits = "Buffalo Gopher designed by [Ashley McNamara](https://twitter.com/ashleymcnamara) — Original Gopher designed by Renee French"

    [languages.en.menu]
    [[languages.en.menu.top]]
        name = 'Documentation'
        url = '/documentation/'
        weight = 3
    [[languages.en.menu.top]]
        name = 'Github'
        url = 'https://github.com/gobuffalo'
        weight = 4
    [[languages.en.menu.top]]
        name = 'Blog'
        url = 'https://blog.gobuffalo.io'
        weight = 5
    [[languages.en.menu.top]]
        name = 'Store'
        url = 'https://store.gobuffalo.io'
        weight = 6
  
  [languages.fr]
    languageName = "English"
    languageCode = "fr-fr"
    weight = 1

    [languages.fr.params]
      copyRight = "Copyright © 2022 Buffalo. Tous droits réservés."
      logoCredits = "Gopher Buffalo conçu par [Ashley McNamara](https://twitter.com/ashleymcnamara) — Gopher originel conçu par Renee French."

    [languages.fr.menu]
        [[languages.fr.menu.top]]
            name = 'Documentation'
            url = '/documentation/'
            weight = 3
        [[languages.fr.menu.top]]
            name = 'GitHub'
            url = 'https://github.com/gobuffalo'
            weight = 4
        [[languages.fr.menu.top]]
            name = 'Blog'
            url = 'https://blog.gobuffalo.io'
            weight = 5
        [[languages.fr.menu.top]]
            name = 'Boutique'
            url = 'https://store.gobuffalo.io'
            weight = 6