baseURL: 'https://gobuffalo.io/'
languageCode: en-us
title: The Buffalo Framework
defaultContentLanguage: en
params:
  goMinVersion: v1.16.0
outputs:
    home: ["HTML", "RSS", "JSON"]
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 2
    params:
      copyRight: Copyright © 2022 Buffalo. All rights reserved.
      logoCredits: >-
        Buffalo Gopher designed by [Ashley
        McNamara](https://twitter.com/ashleymcnamara) — Original Gopher designed
        by Renee French
      documentation: "Documentation"
      tutorials: "Tutorials"
      support: "Support"
      troubleshooting: "Troubleshooting"
      searchPlaceholder: "Search the Buffalo docs"
      noResultsCopy: "We couldn't find any guides or documents with that term. Please try again. You can also visit the documentation site and navigate for more details."
      fromOurBlog: "From our blog"
      learnMore: "Learn more"
      readMore: "Read more"
    menu:
      top:
        - name: Documentation
          url: /documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
        # - name: Store
        #   url: 'https://store.gobuffalo.io'
        #   weight: 6
  fr:
    languageName: French
    languageCode: fr-fr
    weight: 1
    params:
      copyRight: Copyright © 2022 Buffalo. Tous droits réservés.
      logoCredits: >-
        Gopher Buffalo conçu par [Ashley
        McNamara](https://twitter.com/ashleymcnamara) — Gopher originel conçu
        par Renee French.
      documentation: "Documentation"
      tutorials: "Tutoriels"
      support: "Support"
      troubleshooting: "Dépannage"
      searchPlaceholder: "Rechercher dans les documents Buffalo"
      noResultsCopy: "Nous n'avons trouvé aucun guide ou document contenant ce terme. Veuillez réessayer. Vous pouvez également visiter le site de documentation et naviguer pour plus de détails."
      fromOurBlog: "De notre blog"
      learnMore: "Apprendre encore plus"
      readMore: "Lire la suite"
    menu:
      top:
        - name: Documentation
          url: /fr/documentation/
          weight: 3
        - name: Blog
          url: 'https://blog.gobuffalo.io'
          weight: 5
        # - name: Boutique
        #   url: 'https://store.gobuffalo.io'
        #   weight: 6
